; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Mar 19 2021 20:23:56 GMT-0400 (Eastern Daylight Time)
M561 ; clear any bed transform
; G29  ; probe the bed and enable compensation

G28 ; home
G30 P0 X20 Y154 Z-99999 ; probe near a leadscrew
G30 P1 X300 Y280 Z-99999 ; probe near a leadscrew
G30 P2 X300 Y50 Z-99999 S3 ; probe near a leadscrew and calibrate 3 motors



