; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Mar 19 2021 20:23:56 GMT-0400 (Eastern Daylight Time)
M280 P0 S10 ; deploy BLTouch

