; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri Mar 19 2021 20:23:57 GMT-0400 (Eastern Daylight Time)
M280 P0 S90 ; retract BLTouch

